logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              
spring:
  profiles:
    active: test     
server:
  tomcat:
    use-relative-redirects: true
    
---        
spring:
  config:
    activate: 
      on-profile: test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ghksrka9274!
    url: jdbc:mariadb://183.111.242.56:3306/teriwoo87
    username: teriwoo87
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: -1

---        
spring:
  config:
    activate: 
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ghksrka9274!
    url: jdbc:mariadb://localhost:3306/teriwoo87
    username: teriwoo87
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: -1      
